substitutions:
  dark_mode: "true"
  time_24h: "false"
  temp_fahrenheit: "true"

esphome:
  name: bitclock
  friendly_name: Bitclock
  platformio_options:
    build_flags:
      - -DESPHOME_USE_ESP_IDF

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# -------------------
# Core ESPHome services
# -------------------

logger:
  level: DEBUG
  logs:
    e2271ks0c1: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Bitclock Fallback Hotspot"
    password: "bitclock"

captive_portal:

# -------------------
# Time
#  Note: If you're not using Home Assistant, uncomment the following to change the time platform to sntp:
#
#  time:
#    - platform: sntp
#      id: homeassistant_time
#      timezone: "America/Los_Angeles"  # your timezone
# -------------------

time:
  - platform: homeassistant
    id: homeassistant_time

# -------------------
# I2C (Bitclock PCB)
# -------------------

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true

# -------------------
# Sensors
# -------------------

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Relative Humidity"
      id: humidity

  - platform: scd4x
    co2:
      name: "CO2"
      id: co2

  - platform: sgp4x
    voc:
      name: "VOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox

# -------------------
# External E-Ink Driver
# -------------------

external_components:
  - source:
      type: local
      path: /config/esphome/external_components
    components: [ e2271ks0c1 ]

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO1

display:
  - platform: e2271ks0c1
    id: epd

    cs_pin: GPIO10
    dc_pin: GPIO7
    reset_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true

    data_rate: 4MHz
    rotation: 0
    update_interval: 10s
    full_update_every: 100   # Full refresh every 100 updates (16 min) to clear ghosting
    temperature_c: 25

    lambda: |-
      // Display dimensions: 264 x 176
      int w = it.get_width();
      int h = it.get_height();

      // Dark mode: swap foreground and background
      bool dark = ${dark_mode};
      auto fg = dark ? COLOR_OFF : COLOR_ON;
      auto bg = dark ? COLOR_ON : COLOR_OFF;

      // Clear to background color
      it.fill(bg);

      // --- Top bar: Time (left) and WiFi (right) ---
      auto time = id(homeassistant_time).now();
      if (time.is_valid()) {
        if (${time_24h}) {
          it.strftime(8, 6, id(font_time), fg, "%H:%M", time);
        } else {
          it.strftime(8, 6, id(font_time), fg, "%l:%M%P", time);
        }
      } else {
        it.print(8, 6, id(font_time), fg, "--:--");
      }

      // WiFi status icon (top right)
      if (wifi::global_wifi_component->is_connected()) {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F05A9");  // wifi
      } else {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F05AA");  // wifi-off
      }

      // --- Divider line ---
      it.line(0, 42, w, 42, fg);

      // --- Sensor readings in 2x2 grid ---
      int col1 = 12;
      int col2 = w / 2 + 6;
      int row1 = 54;
      int row2 = 110;
      int text_offset = 28;
      int value_offset = 18;
      int icon_y_offset = -5;  // Move icons up to align top with label

      // CO2 (top left)
      it.print(col1, row1 + icon_y_offset, id(font_icons), fg, "\U000F07E4");  // molecule-co2
      it.print(col1 + text_offset, row1, id(font_label), fg, "CO2");
      if (!isnan(id(co2).state)) {
        it.printf(col1, row1 + value_offset, id(font_value), fg, "%.0f ppm", id(co2).state);
      } else {
        it.print(col1, row1 + value_offset, id(font_value), fg, "--");
      }

      // Temperature (top right)
      it.print(col2, row1 + icon_y_offset, id(font_icons), fg, "\U000F050F");  // thermometer
      it.print(col2 + text_offset, row1, id(font_label), fg, "TEMP");
      if (!isnan(id(temperature).state)) {
        bool use_f = ${temp_fahrenheit};
        float temp = use_f ? (id(temperature).state * 9.0f / 5.0f) + 32.0f : id(temperature).state;
        it.printf(col2, row1 + value_offset, id(font_value), fg, use_f ? "%.1f °F" : "%.1f °C", temp);
      } else {
        it.print(col2, row1 + value_offset, id(font_value), fg, "--");
      }

      // Humidity (bottom left)
      it.print(col1, row2 + icon_y_offset, id(font_icons), fg, "\U000F058E");  // water-percent
      it.print(col1 + text_offset, row2, id(font_label), fg, "HUMIDITY");
      if (!isnan(id(humidity).state)) {
        it.printf(col1, row2 + value_offset, id(font_value), fg, "%.0f %%", id(humidity).state);
      } else {
        it.print(col1, row2 + value_offset, id(font_value), fg, "--");
      }

      // VOC (bottom right)
      it.print(col2, row2 + icon_y_offset, id(font_icons), fg, "\U000F0D43");  // air-purifier
      it.print(col2 + text_offset, row2, id(font_label), fg, "VOC");
      if (!isnan(id(voc).state)) {
        it.printf(col2, row2 + value_offset, id(font_value), fg, "%.0f idx", id(voc).state);
      } else {
        it.print(col2, row2 + value_offset, id(font_value), fg, "--");
      }

# -------------------
# Fonts
# -------------------

font:
  # Time display - large and bold
  - file: "gfonts://Roboto@700"
    id: font_time
    size: 32
    glyphs: "0123456789:- amp"

  # Value display - numbers and units
  - file: "gfonts://Roboto@500"
    id: font_value
    size: 24
    glyphs: "0123456789.- pm°CFidx%"

  # Labels
  - file: "gfonts://Roboto@500"
    id: font_label
    size: 14
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /"

  # Material Design Icons
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
    id: font_icons
    size: 24
    glyphs:
      - "\U000F05A9"  # mdi:wifi
      - "\U000F05AA"  # mdi:wifi-off
      - "\U000F07E4"  # mdi:molecule-co2
      - "\U000F050F"  # mdi:thermometer
      - "\U000F058E"  # mdi:water-percent
      - "\U000F0D43"  # mdi:air-purifier
