esphome:
  name: bitclock
  friendly_name: Bitclock
  platformio_options:
    build_flags:
      - -DESPHOME_USE_ESP_IDF
  on_boot:
    priority: -100  # Run after WiFi component starts
    then:
      - script.execute: wifi_setup_check

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# -------------------
# Core ESPHome services
# -------------------

logger:
  level: DEBUG
  logs:
    e2271ks0c1: DEBUG

# Home Assistant API (comment out if using standalone ESPHome)
api:

ota:
  - platform: esphome

# -------------------
# Web Server for configuration
# -------------------

web_server:
  port: 80

# -------------------
# Persistent settings (survives reboot)
# -------------------

globals:
  - id: dark_mode
    type: bool
    restore_value: true
    initial_value: 'true'
  - id: temp_fahrenheit
    type: bool
    restore_value: true
    initial_value: 'true'
  - id: time_24h
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: show_setup_screen
    type: bool
    initial_value: 'false'

# -------------------
# WiFi setup screen logic
#   Shows QR code only after WiFi fails to connect (not during initial boot)
# -------------------

script:
  - id: wifi_setup_check
    mode: restart
    then:
      - delay: 15s  # Wait for WiFi connection attempt
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - globals.set:
                id: show_setup_screen
                value: 'true'
            - component.update: epd

# -------------------
# Settings switches (exposed in web UI and Home Assistant)
# -------------------

switch:
  - platform: template
    name: "Dark Mode"
    id: dark_mode_switch
    icon: "mdi:theme-light-dark"
    lambda: 'return id(dark_mode);'
    turn_on_action:
      - globals.set:
          id: dark_mode
          value: 'true'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd
    turn_off_action:
      - globals.set:
          id: dark_mode
          value: 'false'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd

  - platform: template
    name: "Temperature in Fahrenheit"
    id: temp_f_switch
    icon: "mdi:thermometer"
    lambda: 'return id(temp_fahrenheit);'
    turn_on_action:
      - globals.set:
          id: temp_fahrenheit
          value: 'true'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd
    turn_off_action:
      - globals.set:
          id: temp_fahrenheit
          value: 'false'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd

  - platform: template
    name: "24-Hour Time"
    id: time_24h_switch
    icon: "mdi:clock-outline"
    lambda: 'return id(time_24h);'
    turn_on_action:
      - globals.set:
          id: time_24h
          value: 'true'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd
    turn_off_action:
      - globals.set:
          id: time_24h
          value: 'false'
      - lambda: 'id(epd).force_full_update();'
      - component.update: epd

# -------------------
# WiFi with captive portal
# -------------------

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  on_connect:
    - script.stop: wifi_setup_check
    - globals.set:
        id: show_setup_screen
        value: 'false'
    - component.update: epd

  on_disconnect:
    - script.execute: wifi_setup_check

  ap:
    ssid: "Bitclock Setup"
    password: "bitclock123"

captive_portal:

# QR code for WiFi setup (scan to connect to AP)
qr_code:
  - id: wifi_qr
    value: "WIFI:T:WPA;S:Bitclock Setup;P:bitclock123;;"

# -------------------
# Time
#   Home Assistant: Uses HA time (default below)
#   Standalone: Comment out homeassistant platform and uncomment sntp platform
# -------------------

time:
  - platform: homeassistant
    id: current_time

  # - platform: sntp
  #   id: current_time
  #   timezone: "America/Los_Angeles"  # Change to your timezone

# -------------------
# I2C (Bitclock PCB)
# -------------------

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true

# -------------------
# Sensors
# -------------------

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Relative Humidity"
      id: humidity

  - platform: scd4x
    co2:
      name: "CO2"
      id: co2

  - platform: sgp4x
    voc:
      name: "VOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s

# -------------------
# External E-Ink Driver
#   Home Assistant: Copy components folder to /config/esphome/ and use local path
#   Standalone: Use git source
# -------------------

external_components:
  # Home Assistant Add-on: use local path
  - source:
      type: local
      path: /config/esphome/external_components
    components: [ e2271ks0c1 ]

  # Standalone ESPHome: use git source (comment out local above, uncomment below)
  # - source:
  #     type: git
  #     url: https://github.com/gxlabs/esphome-e2271ks0c1
  #   components: [ e2271ks0c1 ]

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO1

display:
  - platform: e2271ks0c1
    id: epd

    cs_pin: GPIO10
    dc_pin: GPIO7
    reset_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true

    data_rate: 4MHz
    rotation: 0
    update_interval: 10s
    full_update_every: 20
    temperature_c: 25

    lambda: |-
      // Display dimensions: 264 x 176
      int w = it.get_width();
      int h = it.get_height();

      // --- WiFi Setup Screen (shown after WiFi fails to connect) ---
      if (id(show_setup_screen)) {
        it.fill(COLOR_OFF);

        // Title
        it.printf(w / 2, 8, id(font_label), COLOR_ON, TextAlign::TOP_CENTER, "WIFI SETUP");

        // QR code centered (scale=2 makes it ~66px)
        id(wifi_qr).draw(&it, (w - 66) / 2, 28, COLOR_ON, 2);

        // Instructions
        it.printf(w / 2, 100, id(font_label), COLOR_ON, TextAlign::TOP_CENTER, "SCAN QR OR CONNECT TO:");
        it.printf(w / 2, 118, id(font_value), COLOR_ON, TextAlign::TOP_CENTER, "Bitclock Setup");
        it.printf(w / 2, 144, id(font_label), COLOR_ON, TextAlign::TOP_CENTER, "PASSWORD: bitclock123");
        it.printf(w / 2, 162, id(font_label), COLOR_ON, TextAlign::TOP_CENTER, "THEN VISIT 192.168.4.1");

        return;  // Skip normal display
      }

      // --- Normal Display ---
      bool dark = id(dark_mode);
      auto fg = dark ? COLOR_OFF : COLOR_ON;
      auto bg = dark ? COLOR_ON : COLOR_OFF;

      // Clear to background color
      it.fill(bg);

      // --- Top bar: Time (left) and WiFi (right) ---
      auto time = id(current_time).now();
      if (time.is_valid()) {
        if (id(time_24h)) {
          it.strftime(8, 6, id(font_time), fg, "%H:%M", time);
        } else {
          it.strftime(8, 6, id(font_time), fg, "%l:%M%P", time);
        }
      } else {
        it.print(8, 6, id(font_time), fg, "--:--");
      }

      // WiFi strength icon (top right)
      float rssi = id(wifi_signal_db).state;
      if (rssi >= -50) {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F0928");  // wifi-strength-4
      } else if (rssi >= -60) {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F0925");  // wifi-strength-3
      } else if (rssi >= -70) {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F0922");  // wifi-strength-2
      } else {
        it.print(w - 28, 8, id(font_icons), fg, "\U000F091F");  // wifi-strength-1
      }

      // --- Divider line ---
      it.line(0, 42, w, 42, fg);

      // --- Sensor readings in 2x2 grid ---
      int col1 = 12;
      int col2 = w / 2 + 6;
      int row1 = 54;
      int row2 = 110;
      int text_offset = 28;
      int value_y_offset = 17;
      int value_x_offset = 4;
      int icon_y_offset = -5;  // Move icons up to align top with label

      // CO2 (top left)
      it.print(col1, row1 + icon_y_offset, id(font_icons), fg, "\U000F07E4");  // molecule-co2
      it.print(col1 + text_offset, row1, id(font_label), fg, "CO2");
      if (!isnan(id(co2).state)) {
        it.printf(col1 + value_x_offset, row1 + value_y_offset, id(font_value), fg, "%.0f ppm", id(co2).state);
      } else {
        it.print(col1 + value_x_offset, row1 + value_y_offset, id(font_value), fg, "--");
      }

      // Temperature (top right)
      it.print(col2, row1 + icon_y_offset, id(font_icons), fg, "\U000F050F");  // thermometer
      it.print(col2 + text_offset, row1, id(font_label), fg, "TEMP");
      if (!isnan(id(temperature).state)) {
        bool use_f = id(temp_fahrenheit);
        float temp = use_f ? (id(temperature).state * 9.0f / 5.0f) + 32.0f : id(temperature).state;
        it.printf(col2 + value_x_offset, row1 + value_y_offset, id(font_value), fg, use_f ? "%.1f F" : "%.1f C", temp);
      } else {
        it.print(col2 + value_x_offset, row1 + value_y_offset, id(font_value), fg, "--");
      }

      // Humidity (bottom left)
      it.print(col1, row2 + icon_y_offset, id(font_icons), fg, "\U000F058E");  // water-percent
      it.print(col1 + text_offset, row2, id(font_label), fg, "HUMIDITY");
      if (!isnan(id(humidity).state)) {
        it.printf(col1 + value_x_offset, row2 + value_y_offset, id(font_value), fg, "%.0f %%", id(humidity).state);
      } else {
        it.print(col1 + value_x_offset, row2 + value_y_offset, id(font_value), fg, "--");
      }

      // VOC (bottom right)
      it.print(col2, row2 + icon_y_offset, id(font_icons), fg, "\U000F0D43");  // air-purifier
      it.print(col2 + text_offset, row2, id(font_label), fg, "VOC");
      if (!isnan(id(voc).state)) {
        it.printf(col2 + value_x_offset, row2 + value_y_offset, id(font_value), fg, "%.0f idx", id(voc).state);
      } else {
        it.print(col2 + value_x_offset, row2 + value_y_offset, id(font_value), fg, "--");
      }

# -------------------
# Fonts
# -------------------

font:
  # Time display - large and bold
  - file: "gfonts://Roboto@700"
    id: font_time
    size: 32
    glyphs: "0123456789:- amp"

  # Value display - numbers and units
  - file: "gfonts://Roboto@500"
    id: font_value
    size: 24
    glyphs: "0123456789.- %CFABcdefghijklmnopqrstuvwxyz"

  # Labels
  - file: "gfonts://Roboto@500"
    id: font_label
    size: 14
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 /:."

  # Material Design Icons
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
    id: font_icons
    size: 24
    glyphs:
      - "\U000F091F"  # mdi:wifi-strength-1
      - "\U000F0922"  # mdi:wifi-strength-2
      - "\U000F0925"  # mdi:wifi-strength-3
      - "\U000F0928"  # mdi:wifi-strength-4
      - "\U000F092B"  # mdi:wifi-strength-off
      - "\U000F07E4"  # mdi:molecule-co2
      - "\U000F050F"  # mdi:thermometer
      - "\U000F058E"  # mdi:water-percent
      - "\U000F0D43"  # mdi:air-purifier
